/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package at.ac.fhcampuswien

import kotlin.random.Random
import kotlin.system.exitProcess

class App {
    // Game logic for a number guessing game
    fun playNumberGame(digitsToGuess: Int = 4) {
        //TODO: build a menu which calls the functions and works with the return values
        println("LET THE GAMES BEGIN")
        println("You have unlimited guesses, so take your time and use your brain...")
        println("Enter your first guess, you will receive feedback in a form of -> 2:1 for example" +
                "which stands for 2 right digits (not knowing if they are on the right position) and 1 " +
                "right digit which is also on the right position!")
        try {
            // throw IllegalArgumentException when too many or too less digits given
            if (digitsToGuess<1 || digitsToGuess>9) {
                throw IllegalArgumentException("Too many or too less digits")
            }
            // create random number using generateRandomNonRepeatingNumber method
            val number = generateRandomNonRepeatingNumber(digitsToGuess)
            var printed = 0

            // testing: println(number)

            // playing the game until generated number is the same as the input
            while (printed.toString() != number.toString()) {
                // read in input -> readLine or Null -> "!!" means value will never be null
                printed = readlnOrNull()!!.toInt()
                // catching when guessed number and generated number do not have the same length
                if (printed.toString().length != number.toString().length) {
                    println("Input does not have the same length as the given random number: please try " +
                            "again with a number with the length: " + number.toString().length)
                    continue
                }
                println(checkUserInputAgainstGeneratedNumber(printed,number))
            }
            println("You Won")

        } catch (e: Exception) {
            println("Something went wrong... Try again")
            exitProcess(0)
        }
    }

    /**
     * Generates a non-repeating number of a specified length between 1-9.
     *
     * Note: The function is designed to generate a number where each digit is unique and does not repeat.
     * It is important to ensure that the length parameter does not exceed the maximum possible length
     * for non-repeating digits (which is 9 excluding 0 for base-10 numbers).
     *
     * @param length The length of the non-repeating number to be generated.
     *               This dictates how many digits the generated number will have.
     * @return An integer of generated non-repeating number.
     *         The generated number will have a number of digits equal to the specified length and will
     *         contain unique, non-repeating digits.
     * @throws IllegalArgumentException if the length is more than 9 or less than 1.
     */
    val generateRandomNonRepeatingNumber: (Int) -> Int = { length ->
        // set random
        val random = Random(System.currentTimeMillis())
        // create lists, one with digits from 0-9 and an empty one (where we add the values to)
        val digits = (0..9).toMutableList()
        val result = mutableListOf<Int>()
        // iteration from 1 to the given length of the number
        for (i in 1..length) {
            // generate random from 0 to the size of digits
            val index = random.nextInt(0,digits.size)
            // add the value on this index to the result and remove it from the digits list -> so there are no duplicates
            result.add(digits[index])
            digits.removeAt(index)
        }
        result.joinToString("").toInt()
    }

    /**
     * Compares the user's input integer against a generated number for a guessing game.
     * This function evaluates how many digits the user guessed correctly and how many of those
     * are in the correct position. The game generates number with non-repeating digits.
     *
     * Note: The input and the generated number must both be numbers.
     * If the inputs do not meet these criteria, an IllegalArgumentException is thrown.
     *
     * @param input The user's input integer. It should be a number with non-repeating digits.
     * @param generatedNumber The generated number with non-repeating digits to compare against.
     * @return [CompareResult] with two properties:
     *         1. `m`: The number of digits guessed correctly (regardless of their position).
     *         2. `n`: The number of digits guessed correctly and in the correct position.
     *         The result is formatted as "Output: m:n", where "m" and "n" represent the above values, respectively.
     * @throws IllegalArgumentException if the inputs do not have the same number of digits.
     */
    val checkUserInputAgainstGeneratedNumber: (Int, Int) -> CompareResult = { input, generatedNumber ->
        //TODO implement the function

        // counting variables
        var rightDigits = 0
        var completedDigits = 0
        // list containing characters which appear more often -> so the rightDigits count is correct
        val alreadyAdded = mutableListOf<Char>()

        var inputString = input.toString()
        val generatedNumberString = generatedNumber.toString()
        /* testing
        println(inputString)
        println(generatedNumberString)
        */
        try {
            // catching if the length of input and generated number is not the same
            if (inputString.length != generatedNumberString.length) {
                throw IllegalArgumentException("Input and generated Number not same length!")
            }
            // increasing completedDigits and rightDigits in case of guessing the correct number + position
            // iterating through each character (=indices) of the generatedNumberString
            for (i in generatedNumberString.indices) {
                if (inputString[i] == generatedNumberString[i]) {
                    completedDigits++
                    // println(alreadyAdded)
                    if (inputString[i] !in alreadyAdded) {
                        rightDigits++
                    }
                    alreadyAdded.add(inputString[i])
                } else if (inputString[i] in generatedNumberString) {
                    if (inputString[i] !in alreadyAdded) {
                        rightDigits++
                    }
                    alreadyAdded.add(inputString[i])
                }
            }
        // catching exception
        } catch (e: Exception) {
            throw IllegalArgumentException("Input and generated Number do not have the same length!")
        }
        CompareResult(rightDigits, completedDigits)
    }
}

fun main() {
    // TODO: call the App.playNumberGame function with and without default arguments

    println("How many generated digits? Please enter a number from 1 to 9")
    val digits = readlnOrNull()!!.toInt()
    val app = App()
    app.playNumberGame(digits)

}
